src/docker/Dockerfile

The base docker image `dependabot/dependabot-core:***` is 4.3GB is size. Adding our content, the resulting image (`tingle/dependabot-azure-devops:**`) is 4.38GB in size. This impacts the download time in runtime environments like the DevOps extension and Kubernetes Jobs.
Switching to a Ruby base image (`ruby:2.6.6-alpha`) reduces the resulting image by 90% (from 4.38GB to 333.4MB). Since functionality is retained, it becomes preferred to use this as the base image.

Use Ruby as base docker image instead of dependabot so as base image

---

.github/workflows/docker.yml
src/extension/task/index.ts

Publish non-restrictive docker image tags so that the Azure DevOps extension can pull the latest patch or latest minor. For example, 0.1.1, 0.1, and 0 would refer to the same image at push time. Pulling from 0.1 will result in the latest path e.g. 0.1.2 or 0.1.3

Simpler docker tags

---

src/docker/README.md
src/extension/README.md
src/extension/task/index.ts
src/extension/task/task.json
src/script/update-script.rb
templates/README.md
templates/dependabot-template.yml

This PR introduces support for limiting the number of open pull requests. It is similar to the official [open-pull-requests-limit](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#open-pull-requests-limit) variable.

Open pull requests limit

---

src/extension/README.md

The cron syntax was invalid. This fixes the syntax to be the correct representation of daily at 2am UTC

fix cron syntax in readme

---

src/extension/task/task.json

Remove `versioningStrategy` from advanced group as it has `visibleRule` in a different group.
Solves #69

VisibleRule and GroupName conflict fix.

---

src/script/Dockerfile

Fixes for permissions in Docker for the new dependabot images.
See https://github.com/dependabot/dependabot-core/pull/3495 and guided by https://github.com/dependabot/dependabot-script/blob/main/Dockerfile

dependabot Docker image Permissions fix

---

src/extension/task/index.ts
src/extension/task/task.json
src/script/README.md
src/script/update-script.rb

This PR adds support for providing work item ID to be attached to the created pull requests. The upstream support exists but passing it was pending.

Work item support

---

src/extension/task/index.ts
src/extension/task/task.json
src/script/Dockerfile
src/script/README.md
src/script/azure_helpers.rb
src/script/update-script.rb

This PR introduces support for updating Pull Requests in the following workflows:
- resolving merge conflicts (useful for when many pull requests are open)
- closing pull requests for dependencies with newer versions
- setting auto-complete for pull requests created
Notes: Resolving merge conflicts and closure of old pull requests requires the task to be executed.
This addresses issue #34

Updating Pull Requests

---

src/script/update-script.rb

Allow for `versions` to be missing in the entries encoded into `DEPENDABOT_IGNORE`

Allow for null versions DEPENDABOT_IGNORE

---

src/script/update-script.rb

- Ensure `pull_request` is assigned when PR creation has a 201 response
- Raise exception when the PR creation fails
Fixes #81

PR creation fixes

---

src/script/azure_helpers.rb
src/script/update-script.rb

Fixes:
- Extracting branch name before deleting old branch when a new version is available now works.
- When a PR is not created but there is no error, print "exists".

Fixes 2021 04 23

---

src/script/azure_helpers.rb

Rename `branch` to `branch_object` in azure_helpers.rb to prevent conflict with a method named in a similar manner

Fix possible name conflict

---

src/script/azure_helpers.rb
src/script/update-script.rb

Changes to auto complete:
- Added `transitionWorkItems`, always set to `false`.
- `deleteSourceBranch` is fixed to `true`.
- `mergeStrategy` seems to not work with `squash` value, instead fix value to `2` which means squash.

Auto complete fixes

---

src/extension/README.md
src/extension/task/index.ts
src/extension/task/task.json

Replace `DEPENDABOT_DOCKER_IMAGE_TAG` env variable with `dockerImageTag` input hence allow different tasks instances to use different tags/versions.

dockerImageTag as task input

---

src/extension/task/index.ts
src/script/README.md
src/script/update-script.rb

This is an initial attempt to fix #114 fix #112 and other issues related to the usage of this extension with on-premises installations of DevOps.
I did not test this yet and I'm not sure if other changes are required to make the introduction of the new environment variables work.
Looking forward to get some feedback

Make port, protocol and virtual directory configurable for on-premises

---

cronjob-template.yaml
src/extension/README.md
src/extension/task/index.ts
src/extension/task/utils/parseConfigFile.ts
src/script/README.md
src/script/update-script.rb

This PR creates a centralized place for the options similar to the cores `dry-run.rb` script thus easier to maintain them. It also:
1. Sets the dependabot logger
2. Use the default naming for `allow` and `ignore` members.
3. Accommodates for pre-release versions when checking if to close an existing PR

Cleanup and fixes (2021-05-28)

---

src/extension/README.md
src/extension/task/index.ts
src/extension/task/models/IDependabotUpdate.ts
src/extension/task/task.json
src/extension/task/utils/getConfigFromInputs.ts
src/extension/task/utils/parseConfigFile.ts
src/script/README.md
src/script/update-script.rb

This PR adds support for the [`milestone` option](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#milestone). This is expected to the work item identifier in Azure Boards.
As a result:
1. `AZURE_WORK_ITEM_ID` environment variable has been replaced with `DEPENDABOT_MILESTONE`.
2. `workItemId` task input has been renamed to `milestone`.

Support for milestone

---

src/extension/task/models/IDependabotUpdate.ts
src/extension/task/utils/parseConfigFile.ts

`allow` and `ignore` options are now picked correctly by the extension. Fixes #97 
This PR also validates the version set in the configuration

Ignore and Allow bug fix

---

src/extension/README.md
src/extension/task/index.ts
src/extension/task/task.json

Fixes #138 
This is work on supporting an optional task input called `extraEnvironmentVariables`. This will make it possible to pass in extra environment variables to the container that runs dependabot. This will make the task more extensible and capable of being used to debug issues easier. Now you will be able to do the following.
```yaml
- task: dependabot@1
inputs:
...
extraEnvironmentVariables: 'EXCON_DEBUG=1'
```
In this example that environment variable would get read by Excon which is what is used to make the HTTP calls during `update-script.rb`.  This will print out request and response data into your azure devops logs.

Add extraEnvironmentVariables support

---

.prettierignore
src/extension/task/index.ts

- fix: use Record instead of Map to extract and pass `extraEnvironmentVariables`
- chore: prettier-ignore src/extension/task/index.ts
> Fix for Github issue #160
> Relates to #138, #139

Fix for extra environment variables

---

src/extension/task/utils/extractHostname.ts
src/extension/task/utils/getSharedVariables.ts

As explained in https://github.com/tinglesoftware/dependabot-azure-devops/issues/27#issuecomment-768054722 dependabot does not support the older `{organization}.visualstudio.com` URLs.
Even though enabling the new URL on existing organizations should not be problematic, I think there is still value in somehow enabling the old URLs to work without having to force people to switch to the new URL.
I discovered that nowadays Azure DevOps makes it possible to access your repos using `dev.azure.com` **even if your organization settings still say `{organization}.visualstudio.com`.**
Therefore, a quick fix that everyone can do today is to add the following to their azure-pipeline YAML:
``` yaml
- task: dependabot@1
inputs: 
...
extraEnvironmentVariables: 'AZURE_HOSTNAME=dev.azure.com'
```
Since …

Redirect *.visualstudio.com URLs to dev.azure.com

---

src/extension/task/index.ts
src/extension/task/task.json
src/extension/task/utils/getSharedVariables.ts

- Rename `containerRegistry` to `dockerImageRegistry` and `containerRepository` to `dockerImageRepository`.
- `dockerImageRegistry` input should be in the advanced group.
- Fix error forming `dockerImage` variable when appending `dockerImageRegistry`.

Extension fixes

---

src/script/update-script.rb

Dependabot's pub package manager only supports string values for requirements_update_strategy, not symbols
Adjust update script to pass in strings instead of symbols for pub only, so that dependabot pub can work
Addresses crashes documented in issue #297. Testing the docker file on my own Flutter repos now works successfully.

Adjust requirements_update_strategy to fix pub crashes

---

src/extension/task/utils/parseConfigFile.ts

This PR adds support for getting the `dependabot.yml` configuration file from both `.azuredevops` and `.github` folders. That is: `.azuredevops/dependabot.yml` and `.github/dependabot.yml`.

Support GitHub config file

---

README.md
src/extension/README.md
src/extension/task/index.ts
src/extension/task/task.json

Added warning when using explicit inputs instead of a configuration file

Deprecate explicit inputs

---

src/script/update-script.rb

Avoid API error when updating a Pull request when [Commit author email validation](https://docs.microsoft.com/en-us/azure/devops/repos/git/repository-settings?view=azure-devops&tabs=browser#commit-author-email) is enabled.
Should be merged once this [Pull request(dependabot/dependabot-core)](https://github.com/dependabot/dependabot-core/pull/5557) is released (#336, #337 ).

Set author details when updating a pull request

---

cronjob-template.yaml
src/extension/README.md
src/extension/task/index.ts
src/extension/task/models/IDependabotUpdate.ts
src/extension/task/utils/getSharedVariables.ts
src/extension/task/utils/parseConfigFile.ts
src/script/README.md
src/script/update-script.rb

Fixes #317 
While the labels are passed as expected, the labels may not appear on Azure DevOps because it does not have centralized labels/tags. As at now [dependabot-core](https://github.com/dependabot/dependabot-core) filters out any custom labels that you add except `security`, `dependencies`, and the language label e.g.`.NET`.
To understand why, follow the call chain for getting the labels:
[`labels_for_pr`](https://github.com/dependabot/dependabot-core/blob/252cb9a123e82391995797fdac45cb8b6f49cbe7/common/lib/dependabot/pull_request_creator/labeler.rb#L47-L54) -> [`default_labels_for_pr`](https://github.com/dependabot/dependabot-core/blob/252cb9a123e82391995797fdac45cb8b6f49cbe7/common/lib/dependabot/pull_request_creator/labeler.rb#L176-L184) -> …

Support for custom labels

---

cronjob-template.yaml
src/extension/README.md
src/extension/task/index.ts
src/extension/task/models/IDependabotUpdate.ts
src/extension/task/utils/parseConfigFile.ts
src/script/README.md
src/script/update-script.rb

This PR adds support for a branch name separator set in the config file (`/.azuredevops/dependabot.yml` or `/.github/dependabot.yml`).
Example config file using it:
```yaml
version: 2
updates:
- package-ecosystem: "npm"
directory: "/"
pull-request-branch-name:
separator: "-" # can only be "-", _, or / (hyphen, underscore or forward slash)
```
For more information see the [official documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#pull-request-branch-nameseparator).

Branch name separator

---

src/script/update-script.rb

Added support for Kubernetes updates by setting the `kubernetes_updates` option on creation of a `FileFetcher`.
Fixes: #346

Added support for Kubernetes updates

---

README.md
src/extension/README.md
src/extension/task/task.json
src/extension/task/utils/parseConfigFile.ts

Changes to support for the configuration file in the extension:
- Support configuration file paths ending in `.yaml` in addition to `.yml`.
- Recommend use of `.github` folder instead of `.azuredevops` folder for the configuration file hence log a warning.

Configuration file preferences

---

README.md
cronjob-template.yaml
src/extension/task/index.ts
src/extension/task/utils/parseConfigFile.ts

- Set deprecation to be in version `0.11.0` instead of `0.10.0`.
- When `useConfigFile=true` and `targetRepositoryName` input is present, produce a warning.
- Remove hosted version in README.md
- Update tag used in `cronjob-template.yaml`.

Softer deprecation and better warnings

---

src/script/Dockerfile
src/script/entrypoint.sh

Hi, 
I would like to ask you to add this tiny possibility/workaround to execute a command before running dependabot.
As I would like to directly use you docker image, but currently I cannot, due to a [Ruby `Resolv` bug](https://github.com/ruby/resolv/issues/23).
**Background**
The issue I have is that within my network environment the docker host itself cannot resolve any network name, therefore some nameservers are configured, but unfortunately due to the bug (ruby/resolv/issues/23) I need to "patch" the `/etc/resolv.conf` before the image runs.
Currently I create an own docker image which is exactly the same as your images, with just one additional line during startup:
`sed -i 1' s/^/#/' /etc/resolv.conf`
in order to comment out the first nameserver entry which I am having issues with. …

provide a workaround for ruby/resolv/issues/23

---

src/script/update-script.rb

Allow using only private nuget feeds and do not force adding the public `nuget.org` feed
which will be used anyway, if `nuget.config` in repository root is correctly configured.
see:
https://github.com/dependabot/dependabot-core/blob/49b849af53d72f4e6641b0779372c6bda76df375/nuget/lib/dependabot/nuget/update_checker/repository_finder.rb#L128-L138
where `credential_repositories` from `.github/dependabot.yml` (or in our case here from `DEPENDABOT_EXTRA_CREDENTIALS`) 
and `config_file_repositories` from `nuget.config` 
gets added as `known_repositories`.

Allow private feeds only - Do not add nuget.org feed if extra credentials are used

---

src/script/README.md
src/script/update-script.rb

With default configuration the commit is authored with email `noreply@github.com` 
in our ADO Server (OnPrem) installation there is no account with this email, therefore the commit cannot be linked with an ADO account and no profile Icon is shown.
Whereas the PR is correctly linked with the Account:
This PR allows the configuration of the committer author email and account, with these variables
```env
GIT_AUTHOR_EMAIL=myemail@provider.com
GIT_AUTHOR_NAME=ownname
```
within the pipeline task `extraEnvironmentVariables`

Allow customizing of dependabot author email/name

---

src/extension/task/index.ts

I removed the 
The deprecation asks the developer to use a configuration file within the `.azuredevops` folder from v0.11 onwards. As of my understanding `.azuredevops` is deprecated and planned to be not supported in v0.11 as well.

Fix deprecation note

---

cronjob-template.yaml
extension/task/task.json
script/README.md

- Change default value for dockerImageRepository from 0.9 to 0.10
- Update tag versions in the examples to 0.10
- Remove duplicate `groupName`.
- Move `updaterOptions` to the `advanced` group.

Quick updates

---

extension/task/index.ts
extension/task/task.json
extension/task/utils/getSharedVariables.ts
script/README.md
script/azure_helpers.rb
script/update-script.rb

If an optional Branch Policy is enabled (e.g. Check for linked work items) the api call for enabling `AutoComplete` needs to provide the policy config id. Otherwise the policy is set to required (by default) and the auto complete will not work

Allow configuration of optional policies for `AutoComplete`

---

README.md
extension/task/IDependabotConfig.ts
extension/task/index.ts
extension/task/utils/convertPlaceholder.ts
extension/task/utils/getConfigFromInputs.ts
extension/task/utils/parseConfigFile.ts

Add support for the top-level `registries` key in `dependabot.yml`. 
To be able to specify authentication details that Dependabot can use to access private package registries.
solves #50

Support configuration options for private registries in dependabot.yml

---

cronjob-template.yaml
extension/README.md
extension/task/IDependabotConfig.ts
extension/task/index.ts
extension/task/utils/parseConfigFile.ts
script/README.md

When using a config file, the `DEPENDABOT_IGNORE_CONDITIONS` env should not be supplied because the Ruby code reads the config appropriately.
Discourage the use of `DEPENDABOT_IGNORE_CONDITIONS` by removing it from samples.

Respect ignore from config

---

extension/task/utils/extractHostname.ts

Our organization is still on the old url format of *.visualstudio.com. The task isn't detecting the hostname correctly and not changing it to dev.azure.com. I believe there is a bug in the following line:
https://github.com/tinglesoftware/dependabot-azure-devops/blob/76e56ef265e8289f1e4a78308f587919e4f6f847/extension/task/utils/extractHostname.ts#L7
The regex test should probably be: /^(?<prefix>\S+)\.visualstudio\.com$/iu
Without the +, the test would fail for hostnames with more than one character in the subdomain (ie `https://a.visualstudio.com` works but `https://abc.visualstudio.com` doesn't).
Because it wasn't detecting our hostname correctly, it would fail trying to find the repository with the error of `Dependabot::RepoNotFound (Dependabot::RepoNotFound)`

Fix hostname detection for old url formats

---

extension/task/IDependabotConfig.ts
extension/task/index.ts
extension/task/utils/convertPlaceholder.ts
extension/task/utils/extractVirtualDirectory.ts
extension/task/utils/getConfigFromInputs.ts
extension/task/utils/parseConfigFile.ts

Update Regex for placeholder/token replacement for registries to support hyphens and be more readable.
Other commits:
- Added warning when using `DEPENDABOT_EXTRA_CREDENTIALS` and a config file.
- Fix spacing, indentation and typos in a couple of files.

Registries fix regex

---

extension/README.md
extension/task/IDependabotConfig.ts
extension/task/utils/parseConfigFile.ts

When converting registries for npm and docker, the `url` property/element should be replaced with `registry` so as to match the expectation in the Ruby baseline/logic code.
Other:
- Remove `DEPENDABOT_EXTRA_CREDENTIALS` from advanced sample to discourage its use.

Correct property/element name for serialized registries

---

script/Gemfile
script/Gemfile.lock

- Fix Ruby version in Gemfile.
- Update bundler version.
- Uninstall unused `irb` gem.
- Add ARM64 for Darwin in PLATFORMS

Ruby updates

---

extension/task/index.ts

Some ENV variables do not need to be passed over from the task extension unless they do not have their default values. These include:
- `DEPENDABOT_REJECT_EXTERNAL_CODE` which defaults to `false`.
- `DEPENDABOT_FAIL_ON_EXCEPTION` which defaults to `true`.
- `AZURE_AUTO_COMPLETE_IGNORE_CONFIG_IDS` which defaults to an empty array.
- `AZURE_PROTOCOL` which defaults to `https`.
- `AZURE_HOSTNAME` which defaults to `dev.azure.com`.
- `DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK` which defaults to `null`.
Other changes:
- Update comment for auto approve

Reduce env passed from task extension to docker container

---

extension/task/index.ts

In addition to work done in #415, some other ENV should not be passed from the task to the docker container unless they are not using the default values:
- `AZURE_AUTO_APPROVE_PR` which defaults to `false`.
- `AZURE_SET_AUTO_COMPLETE` which defaults to `false`.
- `DEPENDABOT_EXTRA_CREDENTIALS` which defaults to an empty array.
Other changes:
`AZURE_AUTO_COMPLETE_IGNORE_CONFIG_IDS`, `AZURE_AUTO_APPROVE_USER_EMAIL`, and `AZURE_AUTO_APPROVE_USER_TOKEN` should only be passed if their parents are set to `true`.

Further reduce env passed from task extension to docker container

---

script/update-script.rb

Instead of `fetcher_args`, use specific values when fetching configuration file in Ruby script hence set the directory for its fetcher to the root (`/`).
Context:
Internally `Dependabot::Config::FileFetcher` takes a possible path and makes it relative to the directory before checking for existence. See https://github.com/dependabot/dependabot-core/blob/c5cd618812b07ece4a4b53ea18d80ad213b077e7/common/lib/dependabot/config/file_fetcher.rb#L29
#422 added logs so we can now tell when the configuration file loads or not.
Fixes: #399
---
Tested against repo at https://dev.azure.com/tingle/dependabot/_git/repro-399
Log for first update
```txt
GitHub access token has been provided.
Using 'https://dev.azure.com:443/' as API endpoint
Reading configuration file from repository...
Read configuration …
```

Use root directory to fetch configuration file in Ruby script

---

script/update-script.rb

Log conflicting dependencies when `requirements_to_unlock == :update_not_possible`

Log conflicting dependencies when update_not_possible

---

README.md
extension/task/utils/parseConfigFile.ts

Remove supports for `.azuredevops` folder in the extension.

Remove support for .azuredevops folder

---

README.md
advisories-example.json
script/Gemfile
script/Gemfile.lock
script/update-script.rb
script/vulnerabilities.rb

This is a continuation of #430 but now introduces support for querying vulnerabilities from the GraphQL endpoint just for the given ecosystem and package hence smaller payload bodies and no longer need to maintain local data. No additional setup is required except for a GitHub access token with `public_repo` scope.
The query:
```graphql
query($ecosystem: SecurityAdvisoryEcosystem, $package: String) {
securityVulnerabilities(first: 100, ecosystem: $ecosystem, package: $package) {
nodes {
firstPatchedVersion {
identifier
}
vulnerableVersionRange
}
}
}
```
Example variables:
```json
{ "ecosystem": "NUGET", "package": "Newtonsoft.Json" }
```
Example response:
```json
{
"data": {
"securityVulnerabilities": {
"nodes": [
{
"firstPatchedVersion": {
"identifier": "13.0.1"
}, …
```

Pull security vulnerabilities from GitHub's GraphQL endpoint

---

extension/task/IDependabotConfig.ts
extension/task/index.ts
extension/task/utils/getConfigFromInputs.ts
extension/task/utils/parseConfigFile.ts

Make changes to handling limits for open PRs:
- `DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT` always has a value and hence should always be passed from the task to the container.
- Parsed value for `open-pull-requests-limit` should be validated and not default to `5`.

Fix logic for passing open PRs limit

---

script/update-script.rb

Added instrumentation for Excon (HTTP library) by logging from `ActivieSupport::Notifications`.
The logs for responses are not as complete as those for requests because Excon does not have that information available in the response yet. References:
- https://github.com/excon/excon/issues/795
- https://github.com/excon/excon/blob/2d1e2d9fbb6dbfd1e49e16e8aa41876220b3b318/lib/excon/response.rb#L72-L80
Addresses some concerns in #437

Excon instrumentation by logs via ActiveSupport::Notifications

---

script/azure_helpers.rb

Use version 6.0 of the REST API for all requests outside of `dependabot-core`.

Standardize API version for REST API

---

script/azure_helpers.rb
script/update-script.rb

When fetching active pull requests, filter by those created by the current user (owner of the access token). The identifier of the current token is fetched from the `connectionData` API added in #441 .

Limit fetched pull requests to those for the current user (token owner)

---

script/update-script.rb

This PR improves the logic for checking in a PR should be abandoned based on the title. Comes in two parts:
1. Titles for some dependencies may not be the full name. For example `org.junit.jupiter:junit-jupiter` will only hav `junit-jupiter` in the title. This is solved by using `display_name` instead of `name`
2. Dependencies in nested folders have different title formats e.g. `chore(deps): bump dotenv from 9.0.1 to 9.0.2 in /server` vs `chore(deps): bump dotenv from 9.0.1 to 9.0.2 in /server`. This is solved by checking for `{space}to{space}{updated_version}`
Fixes: #446

Improve logic in checking PR title before abandoning

---

extension/task/index.ts
extension/task/utils/parseConfigFile.ts
script/update-script.rb

Added support for cloning and `vendor` in config. Without cloning some ecosystems like `terraform` and `npm_and_yarn` may fail in the file update process.
Fixes: #459

Cloning and vendor support

---

.gitignore
script/update-script.rb

Filter out nil (blank objects) and empty strings which is necessary for situations where the GitHub API response contains null that is converted to nil, or it is an empty string.
For example, npm package named `faker` does not have a patched version as of today; see https://github.com/advisories/GHSA-5w9c-rv96-fr7g

Filter out nil/blank and empty values in security advisories

---

extension/task/index.ts
extension/task/task.json
extension/task/utils/getSharedVariables.ts

Allow selection of which updates to run based on their index in the configuration file.
Sample pipeline:
```yml
steps:
- task: dependabot@1
inputs:
targetUpdateIds: '0;2'  # managed by team 1
```
Sample configuration file:
```yml
version: 2
updates:
- ecosystem: nuget
directory: /service1 # managed by team 1
- ecosystem: nuget
directory: /service2 # managed by team 2
- ecosystem: nuget
directory: /service3 # managed by team 1
```

Support selecting update identifiers

---

script/README.md

* Removed escaping for `DEPENDABOT_EXTRA_CREDENTIALS` and  `DEPENDABOT_ALLOW_CONDITIONS` because values are single quoted
* Added clarification to `GITHUB_ACCESS_TOKEN` that classic token is needed because only it is supported by [GitHub GraphQL API](https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql). With [fine-grained token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-fine-grained-personal-access-token) it will not work

Update examples and clarify which Github token should be used

---

script/update-script.rb

Security-only updates should fail if the vulnerabilities fetcher is null owing to the lack of a GitHub token. This will help with #484

Security only update error

---

script/Gemfile
script/Gemfile.lock
script/vulnerabilities.rb

Switch Vulnerabilities Fetcher to use Octokit hence no longer need `graphql-client`

Switch Vulnerabilities Fetcher to use Octokit

---

script/Gemfile
script/Gemfile.lock

Given that tagged releases of `dependabot-omnibus` are currently slow, this PR is switching to getting the gem directly from git so that we can get more recent changes in here.
This should help in testing #366

Switch dependabot-omnibus gem to be installed from git source

---

script/Dockerfile

Given that tagged releases of `dependabot-core` are currently slow, this PR is switching to basing the docker image on a SHA256 so that we can get more recent changes in here.

Switch dependabot-core base image to a fixed sha

---

.github/dependabot.yml
.github/workflows/docker.yml
.gitmodules
script/Dockerfile
script/Gemfile
script/Gemfile.lock

As a followup to #490, this PR adds a git-submodule to https://github.com/dependabot/dependabot-core hence allowing for weekly updates to actually work. Sourcing gems vis git seems to not work as envisioned.

Source from submodule

---

.github/workflows/docker.yml
README.md
cronjob-template.yaml
docs/docker.md
extension/task/index.ts
extension/task/task.json

This PR adds support for pushing to GitHub Container Registry alongside Docker Hub due to limits in non-authenticated requests. The extension now defaults to using GitHub Container Registry.

Push to GitHub Container Registry alongside Docker Hub

---

.github/dependabot.yml
.github/workflows/docker.yml
.gitmodules
.rubocop.yml
Dockerfile
updater/Gemfile
updater/Gemfile.lock

Remove the dependabot-core git submodule, instead use gems via git. This removes the startup warnings and fixed build failures after updates.

Replace git-submodule with gems via git

---

updater/bin/update-script.rb

Change filtering/mapping to not use the blank method. This likely fails now due to the removal of ActiveSupport in #523 
Filtering is done using `compact` (nulls), `strip` (whitespaces) and `empty.
Fixes #529

Remove use of blank method in filtering

---

updater/bin/azure_helpers.rb
updater/bin/update-script.rb

Set the merge commit message when setting auto complete via `mergeCommitMessage` paramter. This is pulled from the `MessageBuilder`. In addition, the `pull_request_auto_complete` method is updated to match the inbuilt `azure_client.autocomplete_pull_request` and will be replaced once https://github.com/dependabot/dependabot-core/pull/6780 is merged.

Pass mergeCommitMessage when setting auto completing

---

server/Tingle.Dependabot/appsettings.json
server/main.bicep
server/main.json

- Use simpler names for the role assignments
- Only create role assignment for Service Bus if the transport is `ServiceBus`.
- Create `Storage Queue Data Contributor` role assignment when transport is `QueueStorage`.

Fix role assignments

---

updater/bin/update-script.rb

When dependency-type is not set for allow conditions, allow all types

---

docs/server.md
extension/task/utils/getDockerImageTag.ts
server/Tingle.Dependabot.Tests/Workflow/UpdateRunnerTests.cs
server/Tingle.Dependabot/Workflow/WorkflowOptions.cs
server/Tingle.Dependabot/appsettings.json

After accidentally releasing version 1.20.0 instead of version 0.20.0, we have to align the versions now. This PR now aligns the versions in the extension's task logic and in comments.

Fix version alignment

---

server/Tingle.Dependabot/Migrations/20230824083425_InitialCreate.Designer.cs
server/Tingle.Dependabot/Migrations/20230824083425_InitialCreate.cs
server/Tingle.Dependabot/Migrations/MainDbContextModelSnapshot.cs
server/Tingle.Dependabot/Models/MainDbContext.cs
server/Tingle.Dependabot/Models/UpdateJob.cs
server/Tingle.Dependabot/Models/UpdateJobResponse.cs
server/Tingle.Dependabot/Program.cs
server/Tingle.Dependabot/Workflow/UpdateRunner.cs

Setup server endpoints to be reached/used by the updater although the pull request logic is yet to be written hence the CodeQL warnings/alerts.
Endpoints
* `update_jobs/{id}/increment_metric`
* `update_jobs/{id}/record_ecosystem_versions`
* `update_jobs/{id}/update_dependency_list`
* `update_jobs/{id}/mark_as_processed`
* `update_jobs/{id}/record_update_job_error`
* `update_jobs/{id}/close_pull_request`
* `update_jobs/{id}/create_pull_request`

Setup updater server endpoints

---

server/Tingle.Dependabot.Tests/Workflow/UpdateRunnerTests.cs
server/Tingle.Dependabot/Models/UpdateJobResources.cs
server/Tingle.Dependabot/Tingle.Dependabot.csproj
server/Tingle.Dependabot/Workflow/UpdateRunner.cs
server/Tingle.Dependabot/Workflow/WorkflowConfigureOptions.cs
server/Tingle.Dependabot/Workflow/WorkflowOptions.cs
server/Tingle.Dependabot/appsettings.json
server/main.bicep
server/main.json

ContainerApp Jobs are easier to manage and startup faster as compared to ContainerGroups/ContainerInstances. This PR changes the deployment of jobs to the former.
This change will also allow the use of the new update with network restrictions in the future which would have been lots of plumbing work with ContainerInstances.
Running of schedules updates is still triggered using the main application for tracking purposes and also because of timezone and cron validation issues in ContainerApp Jobs. There may be no need to migrate that anyway.

Migrate from ContainerGroups/ContainerInstances to ContainerAppJobs

---

server/Tingle.Dependabot/Extensions/IServiceCollectionExtensions.cs
server/Tingle.Dependabot/Models/Azure/AzdoProject.cs
server/Tingle.Dependabot/Models/Azure/AzdoRepository.cs
server/Tingle.Dependabot/Models/Azure/AzdoRepositoryItem.cs
server/Tingle.Dependabot/Models/Azure/AzdoSubscriptionsQuery.cs
server/Tingle.Dependabot/Models/Management/Project.cs
server/Tingle.Dependabot/Tingle.Dependabot.csproj
server/Tingle.Dependabot/Workflow/AzureDevOpsProvider.cs
server/Tingle.Dependabot/Workflow/SynchronizerConfigurationItem.cs

Replace VSTS/TFS/AzureDevOps libraries with plain HttpClient usage because it is faster and easier to test

Replace VSTS/TFS/AzureDevOps libraries

---

.github/dependabot.yml
README.md
extension/tests/utils/dependabot.yml
server/Tingle.Dependabot.Tests/Samples/dependabot.yml

Previous documentation URL is redirecting to `https://support.github.com`.
This PR updates all occurrences to the new address: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

chore: Updating official documentation doc URL

---

docs/updater.md
extension/task/IDependabotConfig.ts
extension/task/index.ts
extension/task/utils/parseConfigFile.ts
server/Tingle.Dependabot/Models/Dependabot/DependabotConfiguration.cs
server/Tingle.Dependabot/Workflow/UpdateRunner.cs
updater/bin/update_script.rb

In depndabot's version [0.237.0](https://github.com/dependabot/dependabot-core/releases/tag/v0.237.0), types have been introduced in numerous types. In particular, the changes in `Dependabot::Config::UpdateConfig` and `Dependabot::Config::File` result in failing builds when parsing the configuration file because of extra properties (registries). 
To solve the issue:
1. Pass the value in `ignore` via ENV as done in #884 
2. Pass the value in `commit-message` via ENV (this PR)
Consequently, this fixes BOM issues with `commit-message` and removes the need to parse the configuration file in the Ruby script.
Fixes: #861

Pass commit options via an ENV in JSON hence no need to parse the config file in Ruby

---

updater/bin/update_script.rb

This reduces the number of network calls and paves way for re-approval or PRs

Only auto approve or set auto complete when a PR is created or is update

---

updater/bin/azure_helpers.rb

The server already uses version 7.0, but the Ruby scripts were lagging.
This is supported from Azure DevOps Server 2022 onwards and by Azure DevOps Services. https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops#supported-versions
Azure DevOps Server 2022 has been operational since Aug 2022 which is almost 2 years ago.

Use version 7.0 of Azure DevOps API

---

updater/bin/update_script.rb

Fixes #1046. 
References to `RequirementsUpdateStrategy` were missing the Dependabot module name and causing "uninitialized constant" errors when `DEPENDABOT_VERSIONING_STRATEGY` was set.
```log
warning: parser/current is loading parser/ruby33, which recognizes 3.3.3-compliant syntax, but you are running 3.3.1.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
GitHub access token has been provided.
bin/update_script.rb:183:in `<main>': uninitialized constant RequirementsUpdateStrategy (NameError)
"lockfile-only" => RequirementsUpdateStrategy::LockfileOnly,
^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Fix missing module name when referencing RequirementsUpdateStrategy

---

README.md
docs/extension.md
docs/server.md
docs/updater.md
extension/.gitignore

Add basic development guide documentation.
Ignore `*.js` and `*.visx` build artifacts in the extension directory.

Add developer guide documentation; ignore extension build artifacts

---

.github/workflows/updater.yml
docs/updater.md
update-files.ps1
updater/Dockerfile

The "updater" action/workflow should use the dependabot-updater base image that corresponds to the version of dependabot-omnibus set in `updater/Gemfile`. Currently "latest" will always be used, which can create problems as seen in https://github.com/tinglesoftware/dependabot-azure-devops/issues/1190#issuecomment-2212026759 
A new task has been added to `.github/workflows/updater.yml` that will read `updater/Gemfile`, extract the current version of dependabot-omnibus, find the git commit SHA for that version tag, then pass it to `updater/Dockerfile` as an argument.
In local/dev environment, the "latest" image tag is still used. Instructions have been added to the Dockerfile.
I have not tested this in a proper github action run, but have executed the script on a Ubunutu host.
```log
% …
```

Use correct version of dependabot-updater base image when running the 'updater' workflow

---

updater/lib/tinglesoftware/dependabot/clients/azure.rb

Fixes #1198. Regression from https://github.com/tinglesoftware/dependabot-azure-devops/pull/1188.
Missing module name for `SharedHelpers`.

Fix auto-approval; missing module name

---

extension/task/utils/resolveAzureDevOpsIdentities.ts

The function `querySubjectHosted` assumes the value array contains at least one item, but sometimes this is not the case.
When the current implementation is ran the DevOps plugin just halts without a proper exception message.

Validate data length before reading request

---

updater/bin/update_script.rb

Fix #1207
- If an allow condition "dependency-name" is nil, use "*" so that it matches all dependency names; 
- Use wildcard matching instead of regex matching so that "\*" matches the name; previously you'd have to use ".*" for a match, which is not consistent with [official documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow).
Technically, this is a breaking change for the project as any existing `dependabot.yml` configs using allow conditions dependency names with ".*" will be interepted differently now e.g. 
- Before this change "Microsoft.*" would match a dependency named "MicrosoftWindows" (wrong)
- After this change "Microsoft.*" would **not** match a depedency named "MicrosoftWindows" …

Fix allow condition "dependency-name" matching

---

updater/bin/update_script.rb

Fix https://github.com/tinglesoftware/dependabot-azure-devops/issues/652#issuecomment-1668990238
Given this config:
```yml
updates:
- package-ecosystem: nuget
allow:
- dependency-name: Newtonsoft.Json
dependency-type: all
```
Updating a package named `AWSSDK.Lambda` would be allowed; but it shouldn't be since at least one allow rule is defined, but none match the dependency name. 
This happens because `allow_conditions_for` returns `"all"` by default, even if there are no conditions matching the dependency name
- `allow_conditions_for` now returns `nil` if there are **no** allow rules matching the dependency name
- `allow_conditions_for` now returns `"all"` if there **is** an allow rule matching the dependency name, but it doesn't have a `dependency-type` property.

Fix all dependencies being [incorrectly] allowed whenever using allow conditions

---

updater/lib/tinglesoftware/dependabot/commands/update_all_dependencies_synchronous_command.rb
updater/lib/tinglesoftware/dependabot/job.rb

If you have an open Dependabot PR that was created with v1.29 or earlier and then run the "vNext" update script from v1.30, the update fails; The script should ignore any PRs which are not compatible with the new update script.
```log
2024/07/19 06:07:16 INFO <job_1721369191> Found 1 open pull requests(s):
2024/07/19 06:07:16 INFO <job_1721369191>  - #6489: Bump Microsoft.AspNetCore.Authentication.OpenIdConnect from 8.0.6 to 8.0.7
2024/07/19 06:07:16 INFO <job_1721369191> Checking if PR #6489: Bump Microsoft.AspNetCore.Authentication.OpenIdConnect from 8.0.6 to 8.0.7 needs to be updated
2024/07/19 06:07:16 ERROR <job_1721369191> undefined method `[]' for nil
2024/07/19 06:07:16 ERROR <job_1721369191> /home/dependabot/dependabot-updater/lib/tinglesoftware/dependabot/commands/update_all_depe …
```

Fix error when attempting to update a pre-1.30 pull request using the new vNext script

---

updater/lib/tinglesoftware/dependabot/api_clients/azure_api_client.rb
updater/lib/tinglesoftware/dependabot/commands/update_all_dependencies_synchronous_command.rb
updater/lib/tinglesoftware/dependabot/job.rb

If `dependabot.yml` has multiple package ecosystems configured (e.g. NuGet and NPM), the update process for the 2nd package ecosystem will abandon PRs created by the 1st package ecosystem with the close reason "dependencies removed".
Ideally, PRs should be isolated per package ecosystem.
- A new "dependabot.package_manager" PR property is set on all created PRs which contains the associated package ecosystem for the update.
- "fetch_open_pull_requests" will ignore any PRs that are not for the current job package ecosystem

Fix PRs being incorrectly abandoned when using multiple package ecosystems

---

updater/lib/tinglesoftware/dependabot/api_clients/azure_api_client.rb
updater/lib/tinglesoftware/dependabot/commands/update_all_dependencies_synchronous_command.rb
updater/lib/tinglesoftware/dependabot/job.rb

When using `update_script_vnext.rb`, it should log updated file diffs like `update_script.rb` does when pull requests are skipped so that debugging problems is easier to do. 
When `DEPENDABOT_SKIP_PULL_REQUESTS` and `DEPENDABOT_DEBUG` are both `true`, updated file diffs are logged. 
e.g.
```log
2024/07/22 04:38:12 INFO <job_12345> Creating a pull request for 'microsoft'
2024/07/22 04:38:12 INFO <job_12345> Skipping pull request creation as it is disabled for this job.
2024/07/22 04:38:12 DEBUG <job_12345> Staged file changes were:
2024/07/22 04:38:12 DEBUG <job_12345>  ± Updated 'WebApplicationNetCore/WebApplicationNetCore.csproj' in '/'
~~~
--- /tmp/original20240722-7-m2sap4      2024-07-22 04:38:12.679913488 +0000
+++ /tmp/updated20240722-7-6yx8xo       2024-07-22 04:38:12.679913488 …
```

Log updated file diffs when 'skip pull requests' and 'debug' are set

---

updater/lib/tinglesoftware/dependabot/job.rb

If you have more than one group PR open. e.g.
When you run the vNext update script it will update the first group PR, but then close every other group PR with the reason "update_no_longer_possible". e.g.
```log
+---------------------------------------------------------------------------------------------------------------+
|                                      Changes to Dependabot Pull Requests                                      |
+-----------------------------------+---------------------------------------------------------------------------+
| updated                           | Microsoft.AspNetCore.Authentication.OpenIdConnect ( from 8.0.6 to 8.0.7 ) |
| closed: update_no_longer_possible | MSTest.TestAdapter,MSTest.TestFramework                                   | …
```

Fix for group PRs being closed on refresh when nothing has changed

---

updater/lib/tinglesoftware/dependabot/api_clients/azure_api_client.rb

When the open pull request limit is reached, the update process throws an errors, which is not expected.
```log
2024/07/21 23:24:56 INFO <job_1721601109> Submitting Verify.Xunit pull request for creation
2024/07/21 23:24:56 ERROR <job_1721601109> Error processing Verify.Xunit (ArgumentError)
2024/07/21 23:24:56 ERROR <job_1721601109> comparison of String with 1 failed
2024/07/21 23:24:56 ERROR <job_1721601109> /usr/local/lib/ruby/3.3.0/logger.rb:653:in `<'
2024/07/21 23:24:56 ERROR <job_1721601109> /usr/local/lib/ruby/3.3.0/logger.rb:653:in `add'
2024/07/21 23:24:56 ERROR <job_1721601109> /home/dependabot/dependabot-updater/lib/tinglesoftware/dependabot/api_clients/azure_api_client.rb:202:in `open_limit_reached_for_pull_requests'
2024/07/21 23:24:56 ERROR <job_1721601109> …
```

Fix logging error when creating new PR and the open PR limit has been reached

---

updater/bin/update_script.rb
updater/bin/update_script_vnext.rb
updater/lib/tinglesoftware/azure/artifacts_credential_provider.rb
updater/lib/tinglesoftware/nuget/credentials_provider.rb

Allow users to authenticate with private Azure DevOps NuGet feeds without any additional configuration or complicated workarounds. Ideally auth should "just work" like it did in v1.24.
Reduce the number of issues users are having with private NuGet feed auth. e.g. see comments in:
- https://github.com/tinglesoftware/dependabot-azure-devops/issues/921#issuecomment-2162273558
- https://github.com/tinglesoftware/dependabot-azure-devops/issues/1201#issuecomment-2242074907
- https://github.com/tinglesoftware/dependabot-azure-devops/issues/1206#issuecomment-2245030650
- https://github.com/tinglesoftware/dependabot-azure-devops/issues/1232#issuecomment-2245129307
If `DEPENDABOT_EXTRA_CREDENTIALS` contains credentials for an Azure DevOps NuGet feed, the workaround detailed in …

Automatically install the Azure Artifacts Credential Provider if DevOps NuGet feeds are configured

---

README.md
extension/task/task.json
extension/task/utils/parseConfigFile.ts
updater/lib/tinglesoftware/azure/artifacts_credential_provider.rb
updater/lib/tinglesoftware/dependabot/job.rb

Fixes #1232
Fixes #1234
After debugging through #1232, I've realised that `ArtifactsCredentialProvider` should not restrict itself to only "dev.azure.com" feeds; instead it should pass-through credentials to **all** NuGet feeds.
It should be possible to configure NuGet auth for Azure DevOps, Azure DevOps Server, and any third-party NuGet package servers using basic auth. For example, see https://github.com/tinglesoftware/dependabot-azure-devops/issues/1232#issuecomment-2247616424.
- Updated [README.MD](https://github.com/tinglesoftware/dependabot-azure-devops/pull/1241/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) with example of how to auth with a third-party NuGet server requiring basic auth.
- Remove host name whitelisting in …

NuGet feed auth support for Azure DevOps, Azure DevOps Server, and third-party NuGet servers

---

extension/task/index.ts
extension/task/task.json

This should allow private agents with non-standard discovery.
Fixes: #1242

Remove docker demand and rely on `tl.which`

---

README.md
updater/lib/tinglesoftware/azure/artifacts_credential_provider.rb
updater/lib/tinglesoftware/dependabot/overrides/nuget/nuget_config_credential_helpers.rb
updater/lib/tinglesoftware/dependabot/overrides/pull_request_creator/pr_name_prefixer.rb
updater/lib/tinglesoftware/dependabot/setup.rb

Fixes #1243
It should be possible to update dependencies in a .NET Framework project when using:
- Private Azure DevOps NuGet package feeds (e.g. dev.azure.com); or
- Private NuGet package feeds secured with basic auth (e.g. nuget.telerik.com); or
- User defined `nuget.config` package sources and package source mappings
- Updated [README.MD](https://github.com/tinglesoftware/dependabot-azure-devops/pull/1248/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) with example of how to configure private NuGet auth when the source repo contains a `nuget.config` file.
- Added `NuGetConfigCredentialHelpers`, which overrides the default `nuget.config` proxy code within dependabot-core with better code that handles more auth scenarios (see code comments …

Fix nuget.config not using correct credentials during NuGet updates of .NET Framework projects

---

updater/lib/tinglesoftware/dependabot/setup.rb

This is the first step towards adding telemetry to the updater. Useful in debugging of issues and general analytics. It follows what the GitHub hosted version has.

Enable opentelemetry in `updater_script_vnext`

---

.github/workflows/updater.yml
updater/Dockerfile
updater/lib/tinglesoftware/dependabot/setup.rb

This is the second step towards monitoring the updater. Useful in debugging of issues and general analytics. It follows what the GitHub hosted version has.
OpenTelemetry was setup in #1254. Next step is to connect the error handler.

Enable sentry in `updater_script_vnext`

---

updater/bin/update_script.rb
updater/bin/update_script_vnext.rb
updater/lib/tinglesoftware/dependabot/overrides/nuget/nuget_config_credential_helpers.rb
updater/lib/tinglesoftware/dependabot/setup.rb

- When using `update_script.rb`, all the `nuget.config` auth fixes should be applied.
- NuGet should not leak passwords to console output via username. e.g.
```log
MSBuild auto-detection: using msbuild version 'Current' from '/usr/local/dotnet/current/sdk/8.0.300'.
Using credentials from config. UserName: user
An error occurred while retrieving package metadata for 'Microsoft.Graph.5.56.0' from source 'nuget_source_1'.
```
- Require `nuget_config_credential_helpers.rb` in `update_script.rb`
- In `nuget_config_credential_helpers.rb`, if the username and password are the same value, we assume that "token" auth is being used and that the username is not significant, so redact username to something generic to avoid NuGet leaking sensitive information. Given current documentation in …

Backport NuGet auth fix to `update_script`; Prevent NuGet leaking passwords in logs

---

updater/bin/update_script.rb
updater/lib/tinglesoftware/azure/artifacts_credential_provider.rb
updater/lib/tinglesoftware/dependabot/overrides/nuget/nuget_config_credential_helpers.rb
updater/lib/tinglesoftware/dependabot/setup.rb

Fix error "Value cannot be null or empty string. (Parameter 'username')" when using a private NuGet feed with a token formatted as ":{{PAT}}".
Reported by users in these comments:
- https://github.com/tinglesoftware/dependabot-azure-devops/issues/1257#issuecomment-2260619241
- https://github.com/tinglesoftware/dependabot-azure-devops/issues/1257#issuecomment-2298981074
The NuGet username is never set to null/empty; it defaults to "unused" if empty.
e.g.
```ruby
"PAT:12345" --> { "username": "PAT", "password": "12345" }
":12345"    --> { "username": "unused", "password": "12345" }
"12345"     --> { "username": "unused", "password": "12345" }
""          --> { "username": "unused", "password": "" }
```

Fix "Value cannot be null or empty string. (Parameter 'username')"

---

server/Tingle.Dependabot.Tests/Models/DependabotConfigurationTests.cs
server/Tingle.Dependabot.Tests/Models/DependabotUpdateTests.cs
server/Tingle.Dependabot.Tests/PeriodicTasks/MissedTriggerCheckerTaskTests.cs
server/Tingle.Dependabot.Tests/PeriodicTasks/UpdateJobsCleanerTaskTests.cs
server/Tingle.Dependabot.Tests/Samples/dependabot.yml
server/Tingle.Dependabot/Consumers/TriggerUpdateJobsEventConsumer.cs
server/Tingle.Dependabot/Consumers/UpdateJobEventsConsumer.cs
server/Tingle.Dependabot/Controllers/UpdateJobsController.cs
server/Tingle.Dependabot/Models/Dependabot/DependabotConfiguration.cs
server/Tingle.Dependabot/Models/MainDbContext.cs
server/Tingle.Dependabot/Models/Management/UpdateJob.cs
server/Tingle.Dependabot/Workflow/UpdateRunner.cs
server/main.bicep
server/main.json

The extension already supports the directories and groups using `update_script_vnext` but the server lies behind. This standardizes support.
The image tag override for NuGet is removed from the bicep resources because the `1.24` image no longer exists and because we no longer need to override it. If you had deployed the app configuration instance, either manually remove the configuration entry from the Azure portal or redeploy using complete mode (defaults to incremental which does not delete).

Update the server version/component to support directories and groups

---

server/Tingle.Dependabot/Migrations/20240824085208_DirectoriesAndGroups.Designer.cs
server/Tingle.Dependabot/Migrations/20240824085208_DirectoriesAndGroups.cs

I added support for directories and groups in https://github.com/tinglesoftware/dependabot-azure-devops/issues/1294 but forgot to add the database migration. Possibly because I do not have unit tests against the actual database.

Add missing EFCore migration for directories and groups support

---

extension/task/IDependabotConfig.ts
extension/task/utils/parseConfigFile.ts
extension/tests/utils/parseConfigFile.test.ts
server/Tingle.Dependabot.Tests/Workflow/UpdateRunnerTests.cs
server/Tingle.Dependabot/Workflow/UpdateRunner.cs

- Handle setting `index-url` instead of `url` for `python_index` registries in the server version/component.
- Handle setting both `host` and `url` for `composer_repository` registries.
- Better logic around building extra credentials.
> This is likely the last modification before we try to move to the proxy used by `dependabot-cli`.
Resolves: #1307

Improvement to credentials handling

---

updater/lib/dependabot/opentelemetry.rb

This should fix the OpenTelemetry export issue.
It may be reverted in the future when `dependabot-core/updater` makes other changes.
See https://docs.sentry.io/platforms/ruby/tracing/instrumentation/opentelemetry/

Register span processor for sentry to fix OTel export

---

extension/task/task.json

Possible fix for #1312.
The current extension task executes under `Node16`, which doesn't support `URL.canParse` (added in `18.17.0`).
https://nodejs.org/docs/latest-v18.x/api/url.html#urlcanparseinput-base
The latest Microsoft docs suggest using `Node20_1` to keep up to date with the latest `azure-pipelines-task-lib`.
https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#prerequisites
Increasing the Node version to 20 also increases the minimum agent version, which reduces compatibility with old (on-premise?) DevOps agents, mentioned here:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode20.md#specify-minimumagentversion
Migration notes for upgrading to Node 20 are here: …

Update extension task node version from v16 to v20.1

---

server/Tingle.Dependabot/Workflow/UpdateRunner.cs

The library has since been updated; we no longer need a workaround.
See also, https://github.com/Azure/azure-sdk-for-net/issues/38385

Remove workaround for reading ContainerApp Job execution

---

.codespellrc
.prettierignore
CONTRIBUTING.MD
README.md
docs/extension.md
docs/migrations/v1-to-v2.md
docs/server.md
docs/updater.md
extension/README.md

Adds a [contributing guide](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#about-contributing-guidelines) that covers development environment setup and how to locally run the various pull request quality checks (i.e. unit tests, rubocop, codespell, prettier).
Preview: https://github.com/tinglesoftware/dependabot-azure-devops/blob/99b1190446c25576694a6889ac8c0016659468e6/CONTRIBUTING.MD
I have also removed a few entries from `.codespellrc` and `.prettierignore` that don't seem to exist (anymore?).

Add contributing guide; update developer guides

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotCli.ts

Bug fixes for:
- Fix "cannot read property of undefined" error when there is no dependency list stored for the project yet (i.e. [a first-time run](https://dev.azure.com/tingle/dependabot/_build/results?buildId=74147&view=results)).
- Forward the GitHub access token to dependabot-cli; avoids rate-limiting when pulling Docker images
- Set Dependabot job id, which helps when debugging log output containing multiple jobs

Fix "cannot read property of undefined" error; Fix GitHub image pull rate-limiting

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts

Bug fixes for:
- Fix "cannot read property of undefined" error when there are no existing pull requests that can be updated yet (i.e. [a first-time run](https://dev.azure.com/tingle/dependabot/_build/results?buildId=74150&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9)).
- Improved logging to ensure error stack traces are always dumped; helps with debugging future issues

Fix another "cannot read property of undefined" error

---

README.md

Update known experiments list documentation.
v0.278.0 added a new `nuget_native_updater` experiment in https://github.com/dependabot/dependabot-core/pull/10521 for the (C#) NuGet updater to handle the entire update process, from `git clone` all the way through `mark_as_processed`.

Update known experiments list documentation

---

extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts

Fix "cannot read properties of null" error when listing project properties for a project that doesn't have any properties yet.  `getProjectProperties` should just return `undefined` when there are no properties instead of throwing an error.
```log
##[error]Failed to get project properties: TypeError: Cannot read properties of null (reading 'map')
TypeError: Cannot read properties of null (reading 'map')
at AzureDevOpsWebApiClient.getProjectProperties (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.35.923/utils/azure-devops/AzureDevOpsWebApiClient.js:372:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async run (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.35.923/index.js:63:104)
```

Fix "cannot read properties of null" error when listing project properties

---

extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts

Fix "undefined is not iterable" error when listing active pull requests for a project when there aren't any pull requests yet, or the pull requests don't have any properties. `getActivePullRequestProperties` should just return an empty array when there are no pull requests instead of throwing an error.
```log
##[error]Failed to list active pull request properties: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at Function.all (<anonymous>)
at AzureDevOpsWebApiClient.getActivePullRequestProperties (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.35.923/utils/azure-devops/AzureDevOpsWebApiClient.js:74:34)
at process.processTicksAndRejections …
```

Fix "undefined is not iterable" error when listing active pull requests

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotCli.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.ts

Refs #1356.
Dependabot hits `api.github.com` to fetch project info, release notes, and commit messages for dependencies when generating pull request descriptions. Currently these requests are unauthenticated because we do not set the GitHub access token in the job credentials, which leads to errors like:
```log
2024-09-27T18:37:21.5657248Z   proxy | 2024/09/27 18:37:21 [952] Remote response: {"message":"API rate limit exceeded for xxx.xx.xx.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
2024-09-27T18:37:21.5695270Z updater | 2024/09/27 18:37:21 ERROR <job_update_0_npm_and_yarn_all> Error while generating PR …
```

Fix GitHub rate limiting when generating pull request descriptions

---

extension/tasks/dependabotV2/utils/dependabot-cli/DependabotCli.ts

Run `go install dependabot` asynchronously so that logs are streamed to task output in real-time instead of blocking until the process has completed. This removes the hitch that happens when dependabot isn't already installed, which might give the user the impression nothing is happening.

Run `go install dependabot` async; stream logs to task output

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts
extension/tasks/dependabotV2/utils/getSharedVariables.ts

To read/update project properties, the project id is required; Currently we look this up using the [list projects API](https://learn.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-7.1&tabs=HTTP) and then find the project that matches the name we have. This isn't ideal because it adds an extra API call; It is now read from the `System.TeamProjectId` [predefined system variable](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables-devops-services).

Simplify lookups of project id; Reduce APIs calls used to read/update project properties

---

extension/tasks/dependabotV2/index.ts

Fix "cannot read properties of undefined" error that happens if the Dependabot process exits with a non-zero result code or otherwise does not return any outputs.
```log
##vso[task.complete result=Failed;]Cannot read properties of undefined (reading 'filter')
##vso[task.issue type=error;source=TaskInternal;]An unhandled exception occurred: TypeError: Cannot read properties of undefined (reading 'filter')
TypeError: Cannot read properties of undefined (reading 'filter')
at run (/home/rhys/development/dependabot-azure-devops/extension/tasks/dependabotV2/index.js:78:46)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Fix "cannot read properties of undefined" (reading 'filter')

---

extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts

Fixes #1365.
If `target-branch` is not specified in `dependabot.yml`, the repository default branch is used. Currently the default branch name includes the "/refs/heads/" prefix, which was not intentional. This change removes the prefix so that only the actual branch name is returned.

Fix "pull request cannot be activated because the source and/or the target branch no longer exists" error

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/extension.md
extension/.gitignore
extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotCli.ts

Refs #1356.
Upload the flame graph report to pipeline timeline when `System.Debug` is `true`.
This can be used to gain more insights in to performance bottlenecks within the Dependabot update process in situations where the task stalls/freezes/times out.
The report can be found by [downloading the pipeline logs](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops&tabs=windows-agent#view-and-download-logs), in the `Job` folder; This has been documented in a new [troubleshooting](https://github.com/tinglesoftware/dependabot-azure-devops/blob/8b8e0dbe7564b4d044cb5e3016f711d625c75e69/docs/extension.md#troubleshooting-issues) section in the extension docs page.

Upload flame graph report to pipeline timeline when `System.Debug` is `true`

---

extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts

Fixes #1375.
The merge strategy config and default value were not parsed correctly.

Fix merge strategy config parsing and default value

---

extension/tasks/dependabotV2/utils/dependabot/parseConfigFile.ts

Fixes the "unknown package manager" error that happens when using any of the package ecosystems with names that differ between the `dependabot.yml` config file and the dependabot-core/cli code (e.g. "npm" => "npm_and_yarn").
```log
Running Dependabot update job '/tmp/dependabot-jobs/update-1-npm-all/job.yaml'...
/home/vsts/go/bin/dependabot update -f /tmp/dependabot-jobs/update-1-npm-all/job.yaml -o /tmp/dependabot-jobs/update-1-npm-all/scenario.yaml
cli | 2024/09/29 00:21:51 updater failure: unknown package manager: npm
##[error]Dependabot failed with exit code 1
```
This remapping code existed in task V1, but was missed out in V2.

Fix "unknown package manager" error

---

docs/migrations/v1-to-v2.md
extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts

Changes:
- Add support for the "pull-request-branch-name.separator" config option.
- Update V1 -> V2 migration documentation with [list of changes to environment variables](https://github.com/tinglesoftware/dependabot-azure-devops/blob/c8b5fd6a8a8f6fd6b49acfa47171a64fe2c1a778/docs/migrations/v1-to-v2.md#changes-to-environment-variables).
Example using "-" as the branch name separator:

Add support for the "pull-request-branch-name.separator" config option

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts

- If an error occurs when updating the dependency list project property, bubble the error up the stack so that the task eventually fails; Currently it just assumes the update was successful, which makes it difficult for the user to know that there was a problem.
- If the task fails, the task result message now shows the total number of failed "update tasks" (i.e. outputs that could not be processed) rather than the number of failed "update jobs"; This more accurately summaries the number of errors that happen during the overall update process.
```log
Storing the dependency list snapshot for project 'Dependabot'...
##[error]Failed to update project property 'Dependabot.DependencyList': Error: Failed request: (401)
Error: Failed request: (401)
at RestClient.<anonymous> …
```

Raise error and fail task if dependency list project property cannot be updated [when configured]

---

README.md

Update experiments list documentation to match dependabot-omnibus 0.280.0.
Preview: https://github.com/tinglesoftware/dependabot-azure-devops/blob/79bd3071baf4b2d9c2c37ed559244c9cc4fa3bbb/README.md#configuring-experiments

Update experiments list documentation for dependabot-omnibus 0.280.0

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts

Fixes #1409, specifically https://github.com/tinglesoftware/dependabot-azure-devops/issues/1409#issuecomment-2414876700
An error is now thrown if the branch name of new pull request conflicts with an existing branch.

Throw error if branch name of new pull request conflicts with an existing branch

---

extension/tasks/dependabotV1/task.json
extension/tasks/dependabotV2/task.json
extension/vss-extension.json

Tidy up extension and task metadata.
- **Extension now demands `api-version/5.0`**
Previously as seen in #1423, the extension could be installed on any server and would throw errors at PR creation time if the APIs were not available. Now, installation is prevented on servers that don't support the required APIs. 
- **Extension tags have been added**
For better discovery in the Visual Studio marketplace.
- **Extension links have been updated**
Add links for "home", "getstarted", "issues", and "license". The "Q & A" tab on the extension page now links to the GitHub project [discussions page](https://github.com/tinglesoftware/dependabot-azure-devops/discussions), rather than issues page.
- **Task category changed from "Utility" to "Azure Pipelines"**
The previous value was intended for TFS …

Tidy up extension and task metadata

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotCli.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts

Adds additional debug logging to the DevOps API client to better diagnose failed API calls.
This is aimed at helping identify the root cause of #1438, #1413, and any similar issues in the future.

Add additional debug logging for failed DevOps API requests

---

extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.test.ts
extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts

Fixes #1438.
If the same assignee/reviewer identity is defined multiple times in the `dependabot.yml` config, DevOps will reject the pull request with "500 Internal Server Error". e.g.
```yaml
version: 2
updates:
- package-ecosystem: "nuget"
assignees:
- "Team 3"
reviewers:
- "Team 3"
```
This can be fixed by ensuring identities are unique, skipping duplicates.

Fix duplicate reviewer identities causing "500 Internal Server Error" when creating pull requests

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts

Fixes #1460
Ensures that the open pull requests limit cannot be exceeded. The "update all" step will now be skipped if the pull request limit has already been reached, since there is no point running it if no new PRs can be opened.

Fix open pull requests limit being ignored

---

.github/workflows/cleanup.yml
.github/workflows/updater.yml
Rakefile
extension/tasks/dependabotV2/utils/dependabot/parseConfigFile.ts
server/Tingle.Dependabot.Tests/Workflow/UpdateRunnerTests.cs
server/Tingle.Dependabot/Workflow/UpdateRunner.cs
updater/bin/update_script.rb
updater/lib/tinglesoftware/dependabot/job.rb

Add support for dotnet-sdk package ecosystem:
https://github.com/dependabot/dependabot-core/pull/10756
This should only be merged after https://github.com/tinglesoftware/dependabot-azure-devops/pull/1453.

Add support for dotnet-sdk package ecosystem

---

extension/vss-extension.json

@mburumaxwell sorry, I broke the publish workflow; The task id [was renamed during some of the manifest updates](https://github.com/tinglesoftware/dependabot-azure-devops/pull/1451/files), I didn't realise this cannot be renamed once set.
```log
error: Contribution Microsoft.VisualStudio.Services.TaskId.DEPENDABOTTASK is re-using task ID of some other contribution from earlier version. To publish the extension, change the task ID.
```

Restore original task id; Fix publish workflow

---

.husky/pre-commit
package-lock.json
package.json

Adds pre-commit git hooks (via husky) to run prettier and codespell. This removes the need for contributors to manually run `npm run format` and `codespell` prior to commit, it now just happens automatically and will reject the commit if either commands fail.
[`pretty-quick`](https://www.npmjs.com/package/pretty-quick) is used to run prettier on the changed staged files only rather than all files, which keeps the command time to less than a second.
Example of a commit containing formatting and spelling errors:
```console
rhys@dev-vm:~/development/dependabot-azure-devops$ git commit
🔍  Finding changed files since git revision b100a25.
🎯  Found 2 changed files.
✍️  Fixing up extension/tasks/dependabotV2/utils/dependabot-cli/DependabotCli.ts.
✅  Everything is awesome! …
```

Add husky pre-commit git hooks for prettier and codespell

---

CONTRIBUTING.MD
package.json

Fixes https://github.com/tinglesoftware/dependabot-azure-devops/pull/1450#issuecomment-2482445434.
Disable husky git hooks by default, opt-in using `npx husky`. 
The contributing guide has been updated to reflect this change too.

Disable husky git hooks by default, opt-in using `npx husky`

---

extension/tasks/dependabotV2/task.json

This simple PR fixes the typo in the label of the v2 task for the Git Author email address field

Fixed typo in label for v2 Task

---

extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotCli.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts

Refs #1441, #1473.
Don't log output from highly verbose components (e.g. collector, proxy), unless debugging.
In normal happy day scenarios, these logs provide little to no value but consume a lot of space.

Don't log output from highly verbose components, unless debugging

---

.github/workflows/extension.yml
.github/workflows/server.yml
.github/workflows/updater.yml

Update GitVersion tool spec to 6.0.x so that the resolved version stays below 6.1.
Fixes the error:
```
Querying tool versions for GitVersion.Tool@6.x 
Found matching version: 6.1.0
Error: Version spec '6.x' resolved as '6.1.0' does not satisfy the range '>=5.2.0 <6.1.0'.See https://github.com/GitTools/actions/blob/main/docs/versions.md for more information.
```

Fix publish workflows GitVersion tool version error

---

README.md
docs/extension.md
docs/migrations/v1-to-v2.md
extension/README.md
extension/tasks/dependabotV2/task.json
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.ts
extension/tasks/dependabotV2/utils/dependabot/experiments.ts
extension/tasks/dependabotV2/utils/getSharedVariables.ts

More closely match the behavior of the GitHub hosted Dependabot service by using the same default experiments. If the user explicitly sets the `experiments` task input, the default will not be used.
This PR also cleans up some of the documentation, fixes several inaccuracies and removes things which don't add much value anymore (e.g. V1 auth workarounds).

If no experiments are specified, use the GitHub defaults

---

extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.test.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.ts

_Possible_ fix for #1527.
Error:
```json
{
"error-class":"Dependabot::Sorbet::Runtime::InformationalError",
"error-message":"Parameter 'rules': Expected type T::Hash[String, T.untyped], got type NilClass\nCaller: /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:215\nDefinition: /home/dependabot/common/lib/dependabot/dependency_group.rb:36 (Dependabot::DependencyGroup#initialize)"
}
```
Based on the stack trace, it appears that the [`group:` config didn't contain any rules](https://github.com/dependabot/dependabot-core/blame/b6e9029fb65e64f90d81087f8733e12f22cf33b6/updater/lib/dependabot/dependency_group_engine.rb#L30), resulting in an empty object. Dependabot CLI has an [`omitempty` attribute on the `rules` …

Use pattern '*' when group pattern is not specified in config

---

extension/tasks/dependabotV2/utils/dependabot/experiments.ts

When this experiment is enabled by default, it will produce http timeouts and retries, which cause the pipeline to run extremely slow and fail at the end.
The CLI tries to connect to "host.docker.internal" but the server returns the status code 501 (not implemented), so the cli logs "unexpected output type: record_ecosystem_meta".
This will cause a long timeout (see timestamp) and the action is performed 4 times per dependency, so the entire devops pipeline takes us currently ~16 minutes to run and it also cannot be cancelled.

experiments.ts: disable 'enable-record-ecosystem-meta'

---

README.md
extension/tasks/dependabotV2/utils/dependabot/experiments.ts

Update experiment defaults and documentation to match 0.296.0; This helps keep the DevOps Dependabot behavior aligned with what has been observed in GitHub.
Based on this GitHub Dependabot run:
https://github.com/tinglesoftware/dependabot-azure-devops/actions/runs/13232477372/job/36931750293
New experiments that are now enabled by default:
```txt
'nuget-install-dotnet-sdks': true,
'npm-fallback-version-above-v6': true,
'npm-v6-deprecation-warning': true,
'npm-v6-unsupported-error': true,
'python-3-8-deprecation-warning': true,
'python-3-8-unsupported-error': true,
'enable-shared-helpers-command-timeout': true,
'enable-fix-for-pnpm-no-change-error': true,
'enable-engine-version-detection': true,
'avoid-duplicate-updates-package-json': true,
'allow-refresh-for-existing-pr-dependencies': …
```

Update experiment defaults and documentation to match GitHub Dependabot v0.296.0

---

extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.test.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.ts
extension/tasks/dependabotV2/utils/dependabot-cli/interfaces/IDependabotUpdateJobConfig.ts
extension/tasks/dependabotV2/utils/dependabot/parseConfigFile.ts

Fixes #1531.
Fixes https://github.com/tinglesoftware/dependabot-azure-devops/issues/1527#issuecomment-2593877195.
This change attempts to further align the job definition config with what has been observed in GitHub; 
Based on this recent Dependabot run:
https://github.com/tinglesoftware/dependabot-azure-devops/actions/runs/13232477372/job/36931750293
This change should also improve performance when using the default `allow` configuration by only updating **direct** dependencies instead of **all** dependencies, which is inline with what GitHub's Dependabot does; Refs #1518, #1441, https://github.com/tinglesoftware/dependabot-azure-devops/issues/1527#issuecomment-2597028711.
- `allow.dependency-type` now defaults to `direct` instead of `all`
- `ignore.version-requirement` now accepts …

Improved accuracy of Dependabot config handling; Align to observed GitHub behaviour

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/task.json
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotCli.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.ts
extension/tasks/dependabotV2/utils/dependabot/parseConfigFile.ts
extension/tasks/dependabotV2/utils/getSharedVariables.ts

Currently, the extension will always use the latest image for the `dependabot-cli` and `dependabot-updater` components. 
There have been several issues raised recently that essentially boil down to "this was working fine last week, I haven't changed anything". In many cases, these issues happen because there was an upstream change in dependabot-core that changed the behaviour of the updater.
This change aims to allow users to pin a known working version if/when the latest image causes issues.
e.g.
```yaml
steps:
- task: dependabot@2
inputs:
dependabotCliPackage: 'github.com/dependabot/cli/cmd/dependabot@latest'
dependabotUpdaterImage: 'ghcr.io/dependabot/dependabot-updater-{ecosystem}:latest'
```
This change also tidies up the use of "package ecosystem" _(e.g. npm)_ and "package manager" …

Add task input options for overriding `dependabot-cli` package and `dependabot-updater` image

---

README.md
extension/tasks/dependabotV2/utils/dependabot/experiments.ts

Update experiment defaults and documentation to match 0.298.0; This helps keep the DevOps Dependabot behavior aligned with what has been observed in GitHub.
Based on this GitHub Dependabot run:
https://github.com/rhyskoedijk/sbom-azure-devops/actions/runs/13462066397/job/37619521616
New experiments that are now enabled by default:
```txt
'enable-bun-ecosystem': true,
'exclude-local-composer-packages': true,
```
New experiments added to documentation:
|Package Ecosystem|Experiment Name|Value Type|More Information|
|--|--|--|--|
| Composer | exclude_local_composer_packages | true/false| https://github.com/dependabot/dependabot-core/pull/11527 |

Update experiment defaults and documentation to match GitHub Dependabot v0.298.0

---

extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.test.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.ts
extension/tasks/dependabotV2/utils/dependabot/interfaces/IDependabotConfig.ts

Fixes #1550.
I have not been able to test this using a real DevOps Server install; However, by emulating the same configs that would be used in a DevOps Server, I was able to reproduce the issue.
I was not able to confirm if git clone would actually succeed after this change, so it is possible that there _might_ be other errors further in to the update process.

Fix missing virtual directory in `source.repo` config for DevOps Server

---

extension/tasks/dependabotV2/index.test.ts
extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.test.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotJobBuilder.test.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.test.ts
extension/tasks/dependabotV2/utils/github/PackageEcosystem.ts

Fixes #1575
Fixes #1577
These are both regressions introduced recently by https://github.com/tinglesoftware/dependabot-azure-devops/pull/1556 when I attempted to clean up the some of the confusing "package ecosystem" _(e.g. npm)_ and "package manager" _(e.g. npm_and_yarn)_ usage to be more clear. In hindsight, there were more usages of this than I originally thought.
I have updated the variables to be more self-describing and added unit tests to validate the package ecosystem/manager usage.
Unfortunately the diff is hard to follow because I extracted some of the logic in to a function to break down the size of `run()` and make it easier to unit test.

Fix "source branch already exists" and "unknown package ecosystem" errors

---

extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts

This fixes https://github.com/tinglesoftware/dependabot-azure-devops/issues/1499#issuecomment-2681781370
when the project is hosted on azure devops cloud the identity url changes domain to vssps.dev.azure.com. This breaks the connection (WebAPI) since it's configured not to allow requests across multiple origins. 
Since no origin is configured explicitly , the first request will determine the origin and so later in the code when the identity url is invoked the auth header will not be added to the request, causing 401 responses. 
This pr updates the webapi connection to allow the auth handling to support cross domain requests.

support multiple origins by the same connection

---

extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts
extension/tasks/dependabotV2/utils/getSharedVariables.ts

The APIs allow for using the ID or the name. In a number of cases, the API response body contains the ID and not the name in its URL fields. Using the ID will allow this value to be overridden in the future without needing to fetch project information.
This may be reverted later incase it causes issues.

Use the project ID over the Name to allow for easier overriding

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/task.json
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotCli.ts
extension/tasks/dependabotV2/utils/getSharedVariables.ts

This should allow use of self-signed certificates in OnPrem setups.

Add support for `proxyCertPath`, passed to `dependabot-cli`

---

extension/tasks/dependabotV2/index.ts
extension/tasks/dependabotV2/utils/getSharedVariables.ts

Apparently, lots of people believe that since they work in a corporate repo, even the URLs are very secret. While it makes sense in some cases, it more often than not is getting in the way of being able to debug correctly. A new environment variable, `System.Secrets` that is not official but used in this PR, makes it an opt-in functionality.
Resolves: #1551

Make masking of secrets optional via `System.Secrets` ENV (defaults to false)

---

extension/package-lock.json

Fix two package vulnerabilities raised by `npm audit` that have been around for a while.
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn
https://github.com/advisories/GHSA-3xgq-45jj-v275
Severity: moderate
Regular Expression Denial of Service (ReDoS) in micromatch
https://github.com/advisories/GHSA-952p-6rrq-rcjv

Bump cross-spawn from 7.0.3 to 7.0.4 and micromatch from 4.0.7 to 4.0.8; Fix CVE-2024-21538 and CVE-2024-4067 

---

README.md
extension/tasks/dependabotV2/utils/dependabot/experiments.ts

Update experiment defaults and documentation to match 0.300.0; This helps keep the DevOps Dependabot behavior aligned with what has been observed in GitHub.
Based on this GitHub Dependabot run:
https://github.com/rhyskoedijk/sbom-azure-devops/actions/runs/13727416073/job/38396936414

Update experiment defaults and documentation to match GitHub Dependabot v0.300.0

---

extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.test.ts
extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts

The list of dependencies can grow quite large (>10KB in non trivial repos) and may surpass the limit allowed or slow down the AzDo UI which loads all properties. This PR removes that code and outputs an warning instead as we research if there is a valid alternative.
Consequently, all code that access/modifies project properties is also removed as it is unused.

No longer storing dependency list in project properties

---

extension/tasks/dependabotV2/utils/getSharedVariables.ts

In https://github.com/tinglesoftware/dependabot-azure-devops/issues/1593, the `projectId` and `project` variables were merged into one named `project` and containing the ID because we were sure that the ID will always work. However, it is not very readable. This now changes to use the name.

Use project name over ID

---

extension/tasks/dependabotV2/dependabot/output-processor.ts

For some reason, the `DependabotDependenciesSchema` is used to parse when other types besides `update_dependency_list` and being processed. This PR makes the fields in the schema optional to cater to those till a solution comes up.
See #1609

Improve `DependabotDependenciesSchema` and make certain fields optional

---

extension/tasks/dependabotV2/dependabot/cli.ts
extension/tasks/dependabotV2/index.ts

Fixes https://github.com/tinglesoftware/dependabot-azure-devops/issues/1609#issuecomment-2710029621
Currently we process all updates and aggregate the errors in to an array which is only logged at the very end of the task. This has the side-effect of logging errors out of order, which can be seen in https://github.com/tinglesoftware/dependabot-azure-devops/issues/1609#issue-2906495831 and https://github.com/tinglesoftware/dependabot-azure-devops/issues/1609#issuecomment-2710029621 where the Zod validation error is logged **after** all other outputs have already been processed.
This change moves the error logging earlier in to the process so that errors appear directly next to the action that caused them, which makes the logs easier to read and follow.

Log task errors immediately when raised; Do not deferring logging till end of task

---

extension/tasks/dependabotV2/azure-devops/models.ts
extension/tasks/dependabotV2/dependabot/output-processor.test.ts
extension/tasks/dependabotV2/dependabot/output-processor.ts
extension/tasks/dependabotV2/index.test.ts
extension/tasks/dependabotV2/index.ts

Fixes https://github.com/tinglesoftware/dependabot-azure-devops/issues/1609#issuecomment-2710029621
When the user deletes the source branch for a Dependabot pull request, the task will still attempt to run updates for it. This ends up causing "400 Bad Request" errors. e.g.
```log
2025-03-11T13:38:45.9730394Z Error: HTTP GET 'https://dev.azure.com//_apis/git/repositories/.../stats/branches?api-version=5.0&name=dependabot-docker-Development-/-python-3.13.2' failed: 400 Bad Request
2025-03-11T13:38:45.9736384Z     at AzureDevOpsWebApiClient.restApiRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.44.1228/azure-devops/client.js:508:23)
2025-03-11T13:38:45.9737131Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) …
```

Abandon pull requests when the source branch has been deleted

---

.github/workflows/codeql.yml

The default configuration (without the workflow) does not run on PRs from forks which then requires one to skip validations when accepting PRs and that cannot be done on the GitHub app.
The basic configuration is much easier to maintain and it hides in the background.

Added advanced CodeQL workflow

---

server/Tingle.Dependabot/Extensions/ILoggerExtensions.cs
server/Tingle.Dependabot/Models/Management/UpdateJob.cs
server/Tingle.Dependabot/Models/Management/UpdateJobTrigger.cs
server/Tingle.Dependabot/Program.cs
server/Tingle.Dependabot/Tingle.Dependabot.csproj
server/Tingle.Dependabot/Workflow/AzureDevOpsProvider.cs
server/Tingle.Dependabot/Workflow/UpdateRunner.cs
server/Tingle.Dependabot/Workflow/WorkflowConfigureOptions.cs
server/Tingle.Dependabot/Workflow/WorkflowOptions.cs
server/Tingle.Dependabot/appsettings.json
server/main.bicep
server/main.json

This is a simple way to test but it is also useful incase one wants to run on a Raspberry PI or outside Azure though I wonder who the latter guy is.
In this mode, registration of webhooks does not make sense so it is now optional.
Other deployment targets can be added later by the community if needed.

Support deploying to local docker

---

.github/dependabot.yml
.github/workflows/server.yml

This builds multi-arch images (`linux/amd64` and `linux/arm64`) to allow running the server on a Raspberry Pi and on local macOS machines.
- Use `docker/login-action@v3` for login (better).
- Setup builder using `docker/setup-buildx-action@v3`.
- Build multi-arch images using `docker/build-push-action@v5`.

Support `linux/arm64` images for server

---

README.md
extension/tasks/dependabotV2/dependabot/config.ts
extension/tasks/dependabotV2/dependabot/experiments.ts
extension/tasks/dependabotV2/dependabot/job-builder.test.ts
extension/tasks/dependabotV2/dependabot/job-builder.ts
extension/tasks/dependabotV2/dependabot/models.ts

Starting from dependabot-core v0.300.0 and dependabot-cli v1.62.0, `cooldown` config is supported.
See:
- https://github.com/dependabot/dependabot-core/issues/3651#issuecomment-2773808317
- https://github.com/dependabot/dependabot-core/pull/11693
- https://github.com/dependabot/cli/pull/405

Add support for cooldown config

---

extension/tasks/dependabotV2/dependabot/experiments.ts
extension/tasks/dependabotV2/dependabot/output-processor.test.ts
extension/tasks/dependabotV2/dependabot/output-processor.ts

This is the long-term fix for https://github.com/tinglesoftware/dependabot-azure-devops/pull/1537, see https://github.com/tinglesoftware/dependabot-azure-devops/pull/1537#issuecomment-2599117739 for more context.
https://github.com/dependabot/cli/pull/407 will add support for the `record_ecosystem_meta` output in Dependabot-CLI. After it is merged, the `enable-record-ecosystem-meta` experiment will be reenabled, which is what GitHub Dependabot does.
Ultimately, this change adds zero extra functionality to the DevOps Dependabot implementation. However, it does:
1. Keep the behaviour between GitHub and DevOps aligned
2. Remove the special handling that was previously required for this experiment
3. Prevent https://github.com/tinglesoftware/dependabot-azure-devops/pull/1537 from regressing …

Add support for `record_ecosystem_meta` output; Renable `enable-record-ecosystem-meta` experiment by default

---

README.md
extension/README.md
extension/tasks/dependabotV2/azure-devops/client.test.ts
extension/tasks/dependabotV2/azure-devops/client.ts
extension/tasks/dependabotV2/azure-devops/models.ts
extension/tasks/dependabotV2/dependabot/config.ts
extension/tasks/dependabotV2/dependabot/output-processor.ts

This aligns with support for this in deprecation announcement about 2-3 weeks https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
We have always joined assignees and reviewers because Azure DevOps does not have the concept of assignees.
GitHub is deprecating reviewers in favour of CODEOWNERS. This is also something that Azure DevOps does not support but it can be done using Branch Policies.

Remove support for reviewers (assignees remain)

---

extension/src/dependabot/cli.ts

The value is controlled by `System.Debug` which can be set in the pipeline yaml or toggled on the UI for a given run.

Pass `--debug` to dependabot-cli

---

extensions/azure/README.md
extensions/azure/src/dependabot/output-processor.ts
extensions/azure/src/task-v2.ts
extensions/azure/src/utils/shared-variables.ts
extensions/azure/tasks/dependabotV2/task.json
extensions/azure/tests/task-v2.test.ts

When a PR is abandoned, some people do not know why because the input is `commentPullRequests: false` by default. For consistency with the GitHub hosted version, it only makes sense to remove this input and have comments added.

Remove `commentPullRequests` input

---

extensions/azure/eslint.config.mjs
extensions/azure/src/dependabot/branch-name.ts
extensions/azure/tests/dependabot/branch-name.test.ts

When the branch name separator is not a slash, the directory needs to be normalized to respect that.
This also adds tests for `branch-name.ts` and as a result remove unnecessary escapes in RegEx.

Normalize directory in branch name

---

extensions/azure/README.md
extensions/azure/src/dependabot/output-processor.ts
extensions/azure/src/task-v2.ts
extensions/azure/src/utils/shared-variables.ts
extensions/azure/tasks/dependabotV2/task.json
extensions/azure/tests/dependabot/output-processor.test.ts
extensions/azure/tests/task-v2.test.ts

This is better naming and will allow testing other logic besides pull requests later.
`skipPullRequests` will continue to be present for another month.

Add `dryRun` input to replace `skipPullRequests`

---

.changeset/heavy-papayas-brush.md
packages/core/src/dependabot/experiments.ts

As observed at https://github.com/mburumaxwell/dependabot-azure-devops/actions/runs/15529132614/job/43714190436

Update default experiments as of 09 June 2025

---

.changeset/legal-beers-roll.md
extensions/azure/src/dependabot/job-builder.ts
packages/core/src/dependabot/job.ts

Updates across ecosystems is still in development. It needs to merged in the core repo first before we support it. However, to match current job configs and to prevent surprises, we disable it.

Set `multi-ecosystem-update` in job config

---

.changeset/cute-rooms-eat.md
extensions/azure/scripts/update-versions.mjs
extensions/azure/src/azure-devops/client.ts
extensions/azure/src/dependabot/cli.ts
extensions/azure/src/dependabot/job-builder.ts
packages/paklo/fixtures/config/dependabot.yml
packages/paklo/src/dependabot/config.test.ts
packages/paklo/src/dependabot/config.ts

The `||=` operator treats falsy values like `0`, `false`, and `''` as unset, which led to unintended overwrites. Switching to `??=` ensures only null or undefined trigger the default assignment.
Fixes: #1778

Replace ||= with ??= to preserve falsy values in default assignment

---

.changeset/small-bats-lead.md
extensions/azure/src/dependabot/cli.ts
extensions/azure/src/dependabot/models.ts
extensions/azure/src/dependabot/output-processor.ts
extensions/azure/src/task-v2.ts
extensions/azure/tasks/dependabotV2/task.json
extensions/azure/tests/dependabot/output-processor.test.ts
extensions/azure/tests/task-v2.test.ts

To allow other tasks to be chained to be placed after dependabot runs, it makes sense to collect the identifiers of pull requests created/modified/abandoned then output these. This change introduces a comma-separated value is set to a new `affectedPrs` output variable.
It should not be easier to do any other logic that one needs to do such as making reviewers required, sending notifications to Teams, or light up some office lights.

Collect affected PRs for a given run and set output variable

---

.changeset/many-cycles-carry.md
extensions/azure/src/dependabot/cli.ts

Use ||= instead of ??= when finding go/dependabot tool

---

.changeset/puny-seals-send.md
apps/dashboard/prisma/migrations/20251003142314_usage_telemetry/migration.sql
apps/dashboard/prisma/schema.prisma
apps/dashboard/src/app/api/cleanup/usage-telemetry/route.ts
apps/dashboard/src/app/api/usage-telemetry/route.ts
apps/dashboard/src/lib/prisma/client.ts
apps/dashboard/src/middleware.ts
apps/dashboard/vercel.json
packages/paklo/src/azure/jobs-runner.ts
packages/paklo/src/dependabot/index.ts
packages/paklo/src/dependabot/job-runner.ts
packages/paklo/src/dependabot/usage.ts

The information collected is shown in the logs at the end of each job. Nothing sensitive.
This is to help me understand the usage of the tool/extension/cli through a couple of weeks. There is no other source of this information except for when reviews are left but no-one is bothered to leave those or to even want to give feedback via other channels. Do people still use this? Let's find out.
Example payload
```json
{
"trigger": "user",
"provider": "azure",
"owner": "https://dev.azure.com/tingle/",
"package-manager": "terraform",
"host": {
"platform": "darwin",
"release": "25.0.0",
"arch": "arm64",
"machine": "d3bbb66be2ad9dfab10af69b450f7e7e814ef7bbf1277a6d0df9e1db44ba4f5c"
},
"version": "0.9.0",
"id": 4210136136,
"started": "2025-10-03T14:54:25.565Z",
"duration": 29307,
"success": true
} …
```

Add tool usage tracking
