src/extension/package.json, src/extension/task/index.ts, src/extension/task/models/IDependabotUpdate.ts, src/extension/task/task.json, src/extension/task/utils/getDependabotConfigFromInputs.ts, src/extension/task/utils/parseDependabotConfigFile.ts
- Add support for `.azuredevops/dependabot.yml` config file as an option to specify dependency updates configuration
- Enable support multiple dependency update configs from the YAML file 
- Add `useConfigFile `task input to enable/disable the use of the YAML config file
=> Support for dependabot.yml file

src/script/update-script.rb
Check that value for AZURE_SET_AUTO_COMPLETE is set to true when deciding if the PRs should be set to autocomplete
Fixes #92
=> Auto complete fix

src/extension/task/task.json
Reorganize task inputs to resolve issues with offline installations and for a better user experience
=> Reorganize task inputs

.github/workflows/docker.yml, .github/workflows/extension.yml, src/extension/package.json, src/extension/task/utils/parseConfigFile.ts
- Change config to any constraint
- Update `azure-pipelines-task-lib` and `tfx-cli`.
- Update devDependencies
- Change nodejs version used from 10.x to 16.x
- Use major version in gitversion action steps
=> Fixes and updates for 2021 September 27

src/extension/README.md, src/extension/task/index.ts, src/extension/task/task.json, src/extension/task/utils/getSharedVariables.ts, src/script/azure_helpers.rb, src/script/update-script.rb
Fixes #269
I never did any development with azure devops, and I could not figure out how to test this properly.
Does anyone mind lending me a hand?
Thanks!
=> Autocomplete merge type

src/extension/task/index.ts, src/extension/task/task.json, src/extension/task/utils/getSharedVariables.ts
=> Add support for alternative docker registry and repository

src/extension/task/index.ts, src/extension/task/task.json, src/extension/task/utils/extractOrganization.ts, src/extension/task/utils/getAzureDevOpsAccessToken.ts, src/extension/task/utils/getConfigFromInputs.ts, src/extension/task/utils/getGithubAccessToken.ts, src/extension/task/utils/getSharedVariables.ts, src/extension/task/utils/getTargetRepository.ts, src/extension/task/utils/parseConfigFile.ts
- Fix imports in the task
- Change the default docker tag to from 0.6 to 0.7
=> V7 release prep

script/update-script.rb
=> Added missing commas in options

.github/workflows/docker.yml, .github/workflows/extension.yml, .github/workflows/mispell.yml
- Fix indentation in workflow files.
- Exclude `{script,extension}/README.md` files from path triggers.
=> Workflow updates

.gitignore, script/azure_helpers.rb, script/update-script.rb
Various changes to the ruby script(s) for better and easier readability.
Changes:
- Add argument names in auto complete and auto approve steps.
- Rename `sourceRefName` to `source_ref_name`.
- Convert `if` to `unless` where recommended.
- Shorter variable names
- Break long code lines into multiple
- Avoid possibly uninitialised checker variable
- Update control flow when checking for existing PR
- Use one log for the endpoint used
=> Various ruby script improvments

script/update-script.rb
Generate and log PR title when skipping creation as a means to shed more light on #410 
Other changes:
- Check for null when parsing `DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT` to int.
=> Log to shed light on issue 410

.github/workflows/extension.yml, extension/task/task.json
Use node 18 in workflows, and node 16 in the task execution
=> Node updates

extension/task/utils/parseConfigFile.ts
=> Zero is valid for open-pull-requests-limit

script/azure_helpers.rb
=> Fix variables names in pull_request_approve and get_with_token methods

.devcontainer/devcontainer.json
Also, this will get people faster up and running if they are using dev containers in VS Code.
=> Added dev container for extension

updater/bin/update-script.rb
Removes ActiveSupport usage in line with https://github.com/dependabot/dependabot-core/pull/6667
=> Remove ActiveSupport

updater/Gemfile, updater/bin/update-script.rb
Fix the character length limit error by setting it in the `MessageBuilder`.
This reacts to changes made in https://github.com/dependabot/dependabot-core/pull/7487
=> Fix character length limit given new logic changes

copy-updater-files.ps1, server/Tingle.Dependabot/Models/UpdateJobResponse.cs, server/Tingle.Dependabot/Workflow/UpdateRunner.cs, server/Tingle.Dependabot/Workflow/WorkflowConfigureOptions.cs, server/Tingle.Dependabot/Workflow/WorkflowOptions.cs, server/Tingle.Dependabot/appsettings.json, server/main.bicep, server/main.json, updater/lib/dependabot/environment.rb, updater/spec/dependabot/environment_spec.rb, updater/spec/spec_helper.rb
This PR sets up some preliminaries for emulating/mirroring the official dependabot updater.
=> Preliminary new updater setup

.github/workflows/cleanup.yml
=> Exclude major.minor versions as per SemVer from cleanup

server/Tingle.Dependabot/AppSetup.cs, server/Tingle.Dependabot/Consumers/TriggerUpdateJobsEventConsumer.cs, server/Tingle.Dependabot/Tingle.Dependabot.csproj, server/Tingle.Dependabot/Workflow/Synchronizer.cs
New package added in https://github.com/tinglesoftware/dotnet-extensions/pull/214
=> Replace `FlakeId` and `Ksuid` with recently open sourced `Tingle.Extensions.Primitives`

updater/bin/azure_helpers.rb
=> Set `isReapprove=true` when for PRs with auto approve

.rubocop.yml, Rakefile, update-files.ps1, updater/bin/update_script.rb, updater/lib/tinglesoftware/dependabot/clients/azure.rb, updater/lib/tinglesoftware/dependabot/vulnerabilities.rb, updater/spec/dependabot/update_files_command_spec.rb
This is a basic step actual signatures have yet to be added
=> Enable sorbet and update files

updater/lib/tinglesoftware/dependabot/job.rb
Open issue: https://github.com/tinglesoftware/dependabot-azure-devops/issues/1315
=> Fix vNext AZURE_VIRTUAL_DIRECTORY is not working bug

.github/workflows/extension.yml
Share dev extension builds with rhyskoedijk
=> Share dev extension builds with rhyskoedijk

README.md
Update experiments list documentation to match latest code; Experiments which are now default behavior have been removed.
=> Update experiments list documentation

extension/package-lock.json, extension/package.json, extension/tasks/dependabotV2/utils/azure-devops/AzureDevOpsWebApiClient.ts, extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.test.ts, extension/tasks/dependabotV2/utils/dependabot-cli/DependabotOutputProcessor.ts, extension/tests/update_dependency_list/nuget.json, extension/tests/update_dependency_list/pip.json
This will make it easier for when we need to parse the data in project properties into a the UI envisioned in https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1381
=> Use zod to validate data for `update_dependency_list` and stored deps

.github/workflows/cleanup.yml, .github/workflows/extension.yml, .github/workflows/server.yml, .github/workflows/updater.yml
This should fix:
- https://github.com/tinglesoftware/dependabot-azure-devops/security/code-scanning/25
- https://github.com/tinglesoftware/dependabot-azure-devops/security/code-scanning/26
- https://github.com/tinglesoftware/dependabot-azure-devops/security/code-scanning/27
- https://github.com/tinglesoftware/dependabot-azure-devops/security/code-scanning/28
- https://github.com/tinglesoftware/dependabot-azure-devops/security/code-scanning/29
- https://github.com/tinglesoftware/dependabot-azure-devops/security/code-scanning/30
=> Add workflow permissions

server/Tingle.Dependabot/Migrations/20250408113030_AddUpdateJobPlatform.Designer.cs, server/Tingle.Dependabot/Migrations/20250408113030_AddUpdateJobPlatform.cs
=> Add missing migration for UpdateJobPlatform

.gitignore, docs/server.md, server/Tingle.Dependabot/Controllers/ManagementController.cs, server/Tingle.Dependabot/InitialSetupService.cs, server/Tingle.Dependabot/Models/Management/UpdateJobStatus.cs, server/Tingle.Dependabot/Workflow/UpdateRunner.cs, server/docker-compose.dev.yml, server/docker-compose.yml
This solves the issues with docker compose, sets resource limits, and adds compose files.
=> Complete the setup to work with docker compose

.github/workflows/extension.yml, .github/workflows/server.yml, global.json
This should help dependabot but also should be useful for anyone who clones the repo
=> Specify the .NET SDK version in use

extension/src/dependabot/cli.ts
This is meant to make it easier to debug what is sent to dependabot-cli
=> Log the raw job yaml

extension/src/dependabot/cli.ts
Reverts tinglesoftware/dependabot-azure-devops#1709
=> Revert "Pass `--debug` to dependabot-cli"

extension/src/dependabot/job-builder.ts
We should not map registries to credentials again because we already do so in `parseRegistries(...)`. This should therefore pass all the extra keys such as `index-url`, `organization`, etc.
=> Remove duplicate registry credentials mapping

.github/dependabot.yml, .github/workflows/extension.yml, eslint.config.mjs, extension/package.json, extension/src/azure-devops/client.ts, extension/src/azure-devops/models.ts, extension/src/dependabot/branch-name.ts, extension/src/dependabot/cli.ts, extension/src/dependabot/config.ts, extension/src/dependabot/job-builder.ts, extension/src/dependabot/models.ts, extension/src/dependabot/output-processor.ts, extension/src/github.ts, extension/src/task-v2.ts, extension/src/utils/placeholder.ts, extension/src/utils/shared-variables.ts, extension/src/utils/tokens.ts, extension/src/utils/url-parts.ts, extension/tests/azure-devops/client.test.ts, extension/tests/dependabot/config.test.ts, extension/tests/dependabot/job-builder.test.ts, extension/tests/dependabot/output-processor.test.ts, extension/tests/task-v2.test.ts, extension/tests/utils/placeholder.tests.ts, extension/tests/utils/url-parts.tests.ts, extension/tsconfig.json, package.json, pnpm-lock.yaml, tsconfig.json
This is a step towards ensuring better code for the extension and create room for other apps/packages.
=> Add linting with eslint and resolve warnings/errors

advisories-example.json, extensions/azure/src/github.ts
The identifier type and value are used to form the dependency group name
=> Require identifiers for vulnerabilities

.changeset/lazy-cougars-travel.md, packages/paklo/fixtures/jobs/python-pip.yaml, packages/paklo/src/dependabot/job.ts
=> Coerce parsing of updated-at in ignore-conditions

.changeset/huge-gifts-rest.md, extensions/azure/src/dependabot/cli.ts, extensions/azure/src/dependabot/get-config.ts, extensions/azure/src/dependabot/job-builder.ts, extensions/azure/src/github.ts, extensions/azure/src/task-v2.ts, extensions/azure/tests/task-v2.test.ts, packages/paklo/src/dependabot/config.ts, packages/paklo/src/dependabot/job.ts
This is a step towards having more strict typing in the project to ensure we can get "compile-time" errors instead runtime and to improve intellisense hence devex.
=> Script typing improvements

.changeset/yummy-needles-build.md, extensions/azure/src/azure-devops/client.ts, extensions/azure/src/azure-devops/models.ts, extensions/azure/src/dependabot/cli.ts, extensions/azure/src/dependabot/get-config.ts, extensions/azure/src/dependabot/job-builder.ts, extensions/azure/src/dependabot/output-processor.ts, extensions/azure/src/task-v2.ts, extensions/azure/tests/azure-devops/client.test.ts, extensions/azure/tests/task-v2.test.ts, extensions/azure/tsconfig.json, packages/paklo/src/dependabot/branch-name.ts, packages/paklo/src/dependabot/config.ts, packages/paklo/src/dependabot/job.ts
This has propagation for all type signatures and where not possible, temporary inline types are used (e.g. REST models for AzureDevOps client)
=> Complete enforcing of strict typescript

.changeset/tidy-owls-stop.md, extensions/azure/src/utils/shared-variables.ts, extensions/azure/tasks/dependabotV2/task.json
`dryRun` is the solution as described in #1742
=> Remove the `skipPullRequests` input
